---

_You are currently looking at **version 1.0** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-machine-learning/resources/bANLa) course resource._

---

# Assignment 3 - Evaluation

In this assignment you'll train several models and evaluate how effectively they predict instances of fraud.

In [1]:
import numpy as np
import pandas as pd
#import warnings

### Question 1
Import the data from `fraud_data.csv`. What percentage of the observations in the dataset are instances of fraud?

*This function should return a float between 0 and 1.* 

In [2]:
#df_fraud = pd.read_csv('../data/fraud_data.csv')
#df_fraud.head()

In [35]:
def answer_one():
    
#    df_fraud = pd.read_csv('../data/fraud_data.csv')
    df_fraud = pd.read_csv('./fraud_data.csv')
    percent_fraud = df_fraud.Class.value_counts(1)[1]

    # alternate method to get class percentages
    #fraud = np.bincount(df_fraud.Class)[1] / len(df_fraud.Class)
    return percent_fraud

answer_one()

In [4]:
#X = df_fraud.iloc[:,:-1]

In [5]:
#X.head()

In [6]:
#y = df_fraud.iloc[:,-1]

In [7]:
#y.head()

In [11]:
# Use X_train, X_test, y_train, y_test for all of the following questions
from sklearn.model_selection import train_test_split

df = pd.read_csv('./fraud_data.csv')
#df = pd.read_csv('../data/fraud_data.csv')

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

### Question 2

Using `X_train`, `X_test`, `y_train`, and `y_test` (as defined above), train a dummy classifier that classifies everything as the majority class of the training data. What is the accuracy of this classifier? What is the recall?

*This function should a return a tuple with two floats, i.e. `(accuracy score, recall score)`.*

In [12]:
# Accuracy = TP + TN / (TP + TN + FP + FN)

# Precision = TP / (TP + FP)

# Recall = TP / (TP + FN)  Also known as sensitivity, or True Positive Rate

# F1 = 2 * Precision * Recall / (Precision + Recall) 

In [13]:
from sklearn.dummy import DummyClassifier

In [14]:
def answer_two():
    # recall = TP / (TP + FN)
    # accuracy = TP + TN / (TP + TN + FP + FN)
    
    from sklearn.dummy import DummyClassifier
    from sklearn.metrics import recall_score#, accuracy_score
    
    # instead of importing the acc_score module, can just
    # the .score method of the Classifier instance.
    
    clf_dummy = DummyClassifier(strategy = 'most_frequent')
    clf_dummy.fit(X_train, y_train)
    
    y_dummy_pred = clf_dummy.predict(X_test)
    
    recall = recall_score(y_test, y_dummy_pred)
#    accuracy = accuracy_score(y_test, y_dummy_pred)
    accuracy = clf_dummy.score(X_test, y_test)
    
    return (accuracy, recall)

answer_two()

(0.98525073746312686, 0.0)

### Question 3

Using X_train, X_test, y_train, y_test (as defined above), train a SVC classifer using the default parameters. What is the accuracy, recall, and precision of this classifier?

*This function should a return a tuple with three floats, i.e. `(accuracy score, recall score, precision score)`.*

In [15]:
def answer_three():
    # recall = TP / (TP + FN)
    # accuracy = TP + TN / (TP + TN + FP + FN)
    # precision = TP / (TP + FP)
    
    from sklearn.metrics import recall_score, precision_score, accuracy_score
    from sklearn.svm import SVC

    clf_svc = SVC().fit(X_train, y_train)
    y_pred = clf_svc.predict(X_test)
    
#    scores = [accuracy_score, recall_score, precision_score]
#    ans = (score(y_test, y_pred) for score in scores)
    
    accuracy = clf_svc.score(X_test, y_test)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)

    return (accuracy, recall, precision)

answer_three()

(0.99078171091445433, 0.375, 1.0)

### Question 4

Using the SVC classifier with parameters `{'C': 1e9, 'gamma': 1e-07}`, what is the confusion matrix when using a threshold of -220 on the decision function. Use X_test and y_test.

*This function should return a confusion matrix, a 2x2 numpy array with 4 integers.*

In [16]:
def answer_four():
    # precision_recall_curve = ROC? 
    
    from sklearn.metrics import confusion_matrix
    from sklearn.svm import SVC

    clf = SVC(C = 1e9, gamma = 1e-7).fit(X_train, y_train)
    y_scores = clf.decision_function(X_test)
    y_pred = []
    for score in y_scores:
        if score > -220:
            y_pred.append(1)
        else:
            y_pred.append(0)
#    real_vs_pred = list(zip(y_test[:20], y_scores[:20]))
#    for each in first_few:
#        print(each)
#    precision, recall, thresholds = precision_recall_curve(y_test, y_scores)
#    confusion = confusion_matrix(y_test, y_scores)
    
    confusion = confusion_matrix(y_test, y_pred)
    
    return confusion

#confusion_220 = 
answer_four()
#confusion_220

array([[5320,   24],
       [  14,   66]])

### Question 5

Train a logisitic regression classifier with default parameters using X_train and y_train.

For the logisitic regression classifier, create a precision recall curve and a roc curve using y_test and the probability estimates for X_test (probability it is fraud).

Looking at the precision recall curve, what is the recall when the precision is `0.75`?

Looking at the roc curve, what is the true positive rate when the false positive rate is `0.16`?

*This function should return a tuple with two floats, i.e. `(recall, true positive rate)`.*

In [17]:
def answer_five():
        
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import precision_recall_curve, roc_curve

    logit = LogisticRegression().fit(X_train, y_train)
    y_scores = logit.decision_function(X_test)

    precision, recall, thresholds = precision_recall_curve(y_test, y_scores)
    fpr_lg, tpr_lg, _ = roc_curve(y_test, y_scores)
    
#    print(fpr_lg)
#    print(tpr_lg)
    
    recall_75 = recall[precision == .75]
    
    list_fpr = [each for each in fpr_lg]    
    for i in range(len(list_fpr)):
        if ((list_fpr[i] > 0.15) and (list_fpr[i] < .17)):
            idx_16 = i
            break
            
    tpr_16 = tpr_lg[idx_16]
    return (float(recall_75[0]), tpr_16)
    
answer_five()

(0.825, 0.9375)

### Question 6

Perform a grid search over the parameters listed below for a Logisitic Regression classifier, using recall for scoring and the default 3-fold cross validation.

`'penalty': ['l1', 'l2']`

`'C':[0.01, 0.1, 1, 10, 100]`

From `.cv_results_`, create an array of the mean test scores of each parameter combination. i.e.

|      	| `l1` 	| `l2` 	|
|:----:	|----	|----	|
| **`0.01`** 	|    ?	|   ? 	|
| **`0.1`**  	|    ?	|   ? 	|
| **`1`**    	|    ?	|   ? 	|
| **`10`**   	|    ?	|   ? 	|
| **`100`**   	|    ?	|   ? 	|

<br>

*This function should return a 5 by 2 numpy array with 10 floats.* 

*Note: do not return a DataFrame, just the values denoted by '?' above in a numpy array.*

In [18]:
#grid_values = [{'C':[0.01, 0.1, 1, 10, 100]}, 
#               {'penalty':['l1', 'l2']}]

In [18]:
#from sklearn.model_selection import GridSearchCV
#from sklearn.linear_model import LogisticRegression

#logit = LogisticRegression()
#grid_values = [{'C':[0.01, 0.1, 1, 10, 100], 'penalty':['l1', 'l2']}]
#grid_logit_recall = GridSearchCV(logit, param_grid = grid_values, scoring = 'recall')
#grid_logit_recall.fit(X_train,y_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid=[{'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1', 'l2']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='recall', verbose=0)

In [33]:
#grid_logit_recall.cv_results_['mean_test_score'].reshape(5,2)

array([[ 0.66666667,  0.76086957],
       [ 0.80072464,  0.80434783],
       [ 0.8115942 ,  0.8115942 ],
       [ 0.80797101,  0.8115942 ],
       [ 0.80797101,  0.8115942 ]])

In [32]:
#grid_logit_recall.cv_results_['mean_test_score']

array([ 0.66666667,  0.76086957,  0.80072464,  0.80434783,  0.8115942 ,
        0.8115942 ,  0.80797101,  0.8115942 ,  0.80797101,  0.8115942 ])

In [24]:
#test_df = pd.DataFrame(grid_logit_recall.cv_results_)

In [29]:
#for score, params in zip(test_df.mean_test_score, test_df.params):
#    print(params, score)

{'C': 0.01, 'penalty': 'l1'} 0.666666666667
{'C': 0.01, 'penalty': 'l2'} 0.760869565217
{'C': 0.1, 'penalty': 'l1'} 0.800724637681
{'C': 0.1, 'penalty': 'l2'} 0.804347826087
{'C': 1, 'penalty': 'l1'} 0.811594202899
{'C': 1, 'penalty': 'l2'} 0.811594202899
{'C': 10, 'penalty': 'l1'} 0.807971014493
{'C': 10, 'penalty': 'l2'} 0.811594202899
{'C': 100, 'penalty': 'l1'} 0.807971014493
{'C': 100, 'penalty': 'l2'} 0.811594202899


In [23]:
#grid_logit_recall.cv_results_['mean_test_score']

In [24]:
#test_df.head()

In [34]:
def answer_six():
    from sklearn.model_selection import GridSearchCV
    from sklearn.linear_model import LogisticRegression

    logit = LogisticRegression()
    grid_values = [{'C':[0.01, 0.1, 1, 10, 100], 'penalty':['l1', 'l2']}]
    grid_logit_recall = GridSearchCV(logit, param_grid = grid_values, scoring = 'recall')
    grid_logit_recall.fit(X_train,y_train)
    
    ans6 = grid_logit_recall.cv_results_['mean_test_score']
    
    return ans6.reshape(5,2)

answer_six()
#print(clf_grid.shape)

array([[ 0.66666667,  0.76086957],
       [ 0.80072464,  0.80434783],
       [ 0.8115942 ,  0.8115942 ],
       [ 0.80797101,  0.8115942 ],
       [ 0.80797101,  0.8115942 ]])

In [27]:
#%matplotlib notebook
#import seaborn as sns
#import matplotlib.pyplot as plt

# Use the following function to help visualize results from the grid search
#def GridSearch_Heatmap(scores):
#    plt.figure()
#    sns.heatmap(scores.reshape(5,2), xticklabels=['l1','l2'], yticklabels=[0.01, 0.1, 1, 10, 100])
#    plt.yticks(rotation=0);

#GridSearch_Heatmap(answer_six())