---

_You are currently looking at **version 1.0** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-machine-learning/resources/bANLa) course resource._

---

# Assignment 3 - Evaluation

In this assignment you'll train several models and evaluate how effectively they predict instances of fraud.

In [126]:
import numpy as np
import pandas as pd
import warnings

In [131]:
warnings.filterwarnings('ignore')

### Question 1
Import the data from `fraud_data.csv`. What percentage of the observations in the dataset are instances of fraud?

*This function should return a float between 0 and 1.* 

In [2]:
df_fraud = pd.read_csv('../data/fraud_data.csv')
df_fraud.head()

V1        V2        V3        V4        V5        V6        V7  \
0  1.176563  0.323798  0.536927  1.047002 -0.368652 -0.728586  0.084678   
1  0.681109 -3.934776 -3.801827 -1.147468 -0.735540 -0.501097  1.038865   
2  1.140729  0.453484  0.247010  2.383132  0.343287  0.432804  0.093380   
3 -1.107073 -3.298902 -0.184092 -1.795744  2.137564 -1.684992 -2.015606   
4 -0.314818  0.866839 -0.124577 -0.627638  2.651762  3.428128  0.194637   

         V8        V9       V10  ...         V21       V22       V23  \
0 -0.069246 -0.266389  0.155315  ...   -0.109627 -0.341365  0.057845   
1 -0.626979 -2.274423  1.527782  ...    0.652202  0.272684 -0.982151   
2  0.173310 -0.808999  0.775436  ...   -0.003802  0.058556 -0.121177   
3 -0.007181 -0.165760  0.869659  ...    0.130648  0.329445  0.927656   
4  0.670674 -0.442658  0.133499  ...   -0.312774 -0.799494 -0.064488   

        V24       V25       V26       V27       V28  Amount  Class  
0  0.499180  0.415211 -0.581949  0.015472  0.018065    4.67      0  
1  0.165900  0.360251  0.195321 -0.256273  0.056501  912.00      0  
2 -0.304215  0.645893  0.122600 -0.012115 -0.005945    1.00      0  
3 -0.049560 -1.892866 -0.575431  0.266573  0.414184   62.10      0  
4  0.953062 -0.429550  0.158225  0.076943 -0.015051    2.67      0  

[5 rows x 30 columns]

In [15]:
def answer_one():
    
    df_fraud = pd.read_csv('../data/fraud_data.csv')
    percent_fraud = df_fraud.Class.value_counts(1)[1]

    # alternate method to get class percentages
    #fraud = np.bincount(df_fraud.Class)[1] / len(df_fraud.Class)
    return percent_fraud

answer_one()

0.016410823768035772

In [16]:
X = df_fraud.iloc[:,:-1]

In [17]:
X.head()

V1        V2        V3        V4        V5        V6        V7  \
0  1.176563  0.323798  0.536927  1.047002 -0.368652 -0.728586  0.084678   
1  0.681109 -3.934776 -3.801827 -1.147468 -0.735540 -0.501097  1.038865   
2  1.140729  0.453484  0.247010  2.383132  0.343287  0.432804  0.093380   
3 -1.107073 -3.298902 -0.184092 -1.795744  2.137564 -1.684992 -2.015606   
4 -0.314818  0.866839 -0.124577 -0.627638  2.651762  3.428128  0.194637   

         V8        V9       V10   ...         V20       V21       V22  \
0 -0.069246 -0.266389  0.155315   ...   -0.137258 -0.109627 -0.341365   
1 -0.626979 -2.274423  1.527782   ...    1.341809  0.652202  0.272684   
2  0.173310 -0.808999  0.775436   ...   -0.232185 -0.003802  0.058556   
3 -0.007181 -0.165760  0.869659   ...    0.348269  0.130648  0.329445   
4  0.670674 -0.442658  0.133499   ...    0.402329 -0.312774 -0.799494   

        V23       V24       V25       V26       V27       V28  Amount  
0  0.057845  0.499180  0.415211 -0.581949  0.015472  0.018065    4.67  
1 -0.982151  0.165900  0.360251  0.195321 -0.256273  0.056501  912.00  
2 -0.121177 -0.304215  0.645893  0.122600 -0.012115 -0.005945    1.00  
3  0.927656 -0.049560 -1.892866 -0.575431  0.266573  0.414184   62.10  
4 -0.064488  0.953062 -0.429550  0.158225  0.076943 -0.015051    2.67  

[5 rows x 29 columns]

In [18]:
y = df_fraud.iloc[:,-1]

In [20]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [22]:
# Use X_train, X_test, y_train, y_test for all of the following questions
from sklearn.model_selection import train_test_split

df = pd.read_csv('../data/fraud_data.csv')

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

### Question 2

Using `X_train`, `X_test`, `y_train`, and `y_test` (as defined above), train a dummy classifier that classifies everything as the majority class of the training data. What is the accuracy of this classifier? What is the recall?

*This function should a return a tuple with two floats, i.e. `(accuracy score, recall score)`.*

In [25]:
# Accuracy = TP + TN / (TP + TN + FP + FN)

# Precision = TP / (TP + FP)

# Recall = TP / (TP + FN)  Also known as sensitivity, or True Positive Rate

# F1 = 2 * Precision * Recall / (Precision + Recall) 

In [28]:
from sklearn.dummy import DummyClassifier

In [31]:
def answer_two():
    # recall = TP / (TP + FN)
    # accuracy = TP + TN / (TP + TN + FP + FN)
    
    from sklearn.dummy import DummyClassifier
    from sklearn.metrics import recall_score#, accuracy_score
    
    # instead of importing the acc_score module, can just
    # the .score method of the Classifier instance.
    
    clf_dummy = DummyClassifier(strategy = 'most_frequent')
    clf_dummy.fit(X_train, y_train)
    
    y_dummy_pred = clf_dummy.predict(X_test)
    
    recall = recall_score(y_test, y_dummy_pred)
#    accuracy = accuracy_score(y_test, y_dummy_pred)
    accuracy = clf_dummy.score(X_test, y_test)
    
    return (accuracy, recall)

answer_two()

(0.98525073746312686, 0.0)

### Question 3

Using X_train, X_test, y_train, y_test (as defined above), train a SVC classifer using the default parameters. What is the accuracy, recall, and precision of this classifier?

*This function should a return a tuple with three floats, i.e. `(accuracy score, recall score, precision score)`.*

In [38]:
def answer_three():
    # recall = TP / (TP + FN)
    # accuracy = TP + TN / (TP + TN + FP + FN)
    # precision = TP / (TP + FP)
    
    from sklearn.metrics import recall_score, precision_score, accuracy_score
    from sklearn.svm import SVC

    clf_svc = SVC().fit(X_train, y_train)
    y_pred = clf_svc.predict(X_test)
    
#    scores = [accuracy_score, recall_score, precision_score]
#    ans = (score(y_test, y_pred) for score in scores)
    
    accuracy = clf_svc.score(X_test, y_test)
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)

    return (accuracy, recall, precision)

answer_three()

(0.99078171091445433, 0.375, 1.0)

### Question 4

Using the SVC classifier with parameters `{'C': 1e9, 'gamma': 1e-07}`, what is the confusion matrix when using a threshold of -220 on the decision function. Use X_test and y_test.

*This function should return a confusion matrix, a 2x2 numpy array with 4 integers.*

In [64]:
def answer_four():
    # precision_recall_curve = ROC? 
    
    from sklearn.metrics import confusion_matrix
    from sklearn.svm import SVC

    clf = SVC(C = 1e9, gamma = 1e-7).fit(X_train, y_train)
    y_scores = clf.decision_function(X_test)
    y_pred = []
    for score in y_scores:
        if score > -220:
            y_pred.append(1)
        else:
            y_pred.append(0)
#    real_vs_pred = list(zip(y_test[:20], y_scores[:20]))
#    for each in first_few:
#        print(each)
#    precision, recall, thresholds = precision_recall_curve(y_test, y_scores)
#    confusion = confusion_matrix(y_test, y_scores)
    
    confusion = confusion_matrix(y_test, y_pred)
    
    return confusion

confusion_220 = answer_four()
confusion_220

array([[5320,   24],
       [  14,   66]])

### Question 5

Train a logisitic regression classifier with default parameters using X_train and y_train.

For the logisitic regression classifier, create a precision recall curve and a roc curve using y_test and the probability estimates for X_test (probability it is fraud).

Looking at the precision recall curve, what is the recall when the precision is `0.75`?

Looking at the roc curve, what is the true positive rate when the false positive rate is `0.16`?

*This function should return a tuple with two floats, i.e. `(recall, true positive rate)`.*

In [132]:
def answer_five():
        
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import precision_recall_curve, roc_curve

    logit = LogisticRegression().fit(X_train, y_train)
    y_scores = logit.decision_function(X_test)

    precision, recall, thresholds = precision_recall_curve(y_test, y_scores)
    fpr_lg, tpr_lg, _ = roc_curve(y_test, y_scores)

    recall_75 = recall[precision == .75]
    
    list_fpr = [each for each in fpr_lg]    
    for each in list_fpr:
        if ((each > 0.15) and (each < .17)):
            idx_16 = each
            print(idx_16)
            break
    tpr_16 = tpr_lg[idx_16]
#    ans_tpr = np.array(tpr_16)
    
    return (recall_75[0], tpr_16)
    
answer_five()

0.159618263473


(0.82499999999999996, 0.012500000000000001)

In [ ]:
GridSearchCV.

### Question 6

Perform a grid search over the parameters listed below for a Logisitic Regression classifier, using recall for scoring and the default 3-fold cross validation.

`'penalty': ['l1', 'l2']`

`'C':[0.01, 0.1, 1, 10, 100]`

From `.cv_results_`, create an array of the mean test scores of each parameter combination. i.e.

|      	| `l1` 	| `l2` 	|
|:----:	|----	|----	|
| **`0.01`** 	|    ?	|   ? 	|
| **`0.1`**  	|    ?	|   ? 	|
| **`1`**    	|    ?	|   ? 	|
| **`10`**   	|    ?	|   ? 	|
| **`100`**   	|    ?	|   ? 	|

<br>

*This function should return a 5 by 2 numpy array with 10 floats.* 

*Note: do not return a DataFrame, just the values denoted by '?' above in a numpy array.*

In [ ]:
grid_values = [{'C':[0.01, 0.1, 1, 10, 100]}, 
               {'penalty':['l1', 'l2']}]

In [159]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

logit = LogisticRegression()
grid_values = [{'C':[0.01, 0.1, 1, 10, 100], 'penalty':['l1', 'l2']}]
grid_logit_recall = GridSearchCV(logit, param_grid = grid_values, scoring = 'recall')
grid_logit_recall.fit(X_train,y_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid=[{'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1', 'l2']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='recall', verbose=0)

In [160]:
grid_logit_recall.cv_results_

{'mean_fit_time': array([ 0.07075373,  0.13825067,  0.09112589,  0.23810641,  0.21485003,
         0.29121057,  0.33635036,  0.3446397 ,  0.47526574,  0.33310199]),
 'mean_score_time': array([ 0.0028077 ,  0.0027403 ,  0.00266774,  0.00291491,  0.00399558,
         0.00239428,  0.00268157,  0.00255132,  0.00279927,  0.00236734]),
 'mean_test_score': array([ 0.66666667,  0.76086957,  0.80072464,  0.80434783,  0.8115942 ,
         0.8115942 ,  0.80797101,  0.8115942 ,  0.80797101,  0.8115942 ]),
 'mean_train_score': array([ 0.68115942,  0.77355072,  0.80615942,  0.8134058 ,  0.81884058,
         0.81702899,  0.82427536,  0.82427536,  0.82427536,  0.82427536]),
 'param_C': masked_array(data = [0.01 0.01 0.1 0.1 1 1 10 10 100 100],
              mask = [False False False False False False False False False False],
        fill_value = ?),
 'param_penalty': masked_array(data = ['l1' 'l2' 'l1' 'l2' 'l1' 'l2' 'l1' 'l2' 'l1' 'l2'],
              mask = [False False False False False False Fals

In [169]:
test_df = pd.DataFrame(grid_logit_recall.cv_results_)

In [163]:
grid_logit_recall.cv_results_['mean_test_score']

array([ 0.66666667,  0.76086957,  0.80072464,  0.80434783,  0.8115942 ,
        0.8115942 ,  0.80797101,  0.8115942 ,  0.80797101,  0.8115942 ])

In [170]:
test_df.head()

mean_fit_time  mean_score_time  mean_test_score  mean_train_score param_C  \
0       0.070754         0.002808         0.666667          0.681159    0.01   
1       0.138251         0.002740         0.760870          0.773551    0.01   
2       0.091126         0.002668         0.800725          0.806159     0.1   
3       0.238106         0.002915         0.804348          0.813406     0.1   
4       0.214850         0.003996         0.811594          0.818841       1   

  param_penalty                        params  rank_test_score  \
0            l1  {'C': 0.01, 'penalty': 'l1'}               10   
1            l2  {'C': 0.01, 'penalty': 'l2'}                9   
2            l1   {'C': 0.1, 'penalty': 'l1'}                8   
3            l2   {'C': 0.1, 'penalty': 'l2'}                7   
4            l1     {'C': 1, 'penalty': 'l1'}                3   

   split0_test_score  split0_train_score  split1_test_score  \
0           0.706522            0.690217           0.695652   
1           0.804348            0.771739           0.750000   
2           0.804348            0.798913           0.836957   
3           0.826087            0.809783           0.836957   
4           0.826087            0.820652           0.836957   

   split1_train_score  split2_test_score  split2_train_score  std_fit_time  \
0            0.673913           0.597826            0.679348      0.008460   
1            0.766304           0.728261            0.782609      0.006074   
2            0.798913           0.760870            0.820652      0.015231   
3            0.804348           0.750000            0.826087      0.029731   
4            0.809783           0.771739            0.826087      0.024320   

   std_score_time  std_test_score  std_train_score  
0        0.000761        0.048879         0.006778  
1        0.000659        0.031999         0.006778  
2        0.000480        0.031168         0.010248  
3        0.000752        0.038685         0.009237  
4        0.001887        0.028529         0.006778

In [166]:
def answer_six():
    from sklearn.model_selection import GridSearchCV
    from sklearn.linear_model import LogisticRegression

    logit = LogisticRegression()
    grid_values = [{'C':[0.01, 0.1, 1, 10, 100], 'penalty':['l1', 'l2']}]
    grid_logit_recall = GridSearchCV(logit, param_grid = grid_values, scoring = 'recall')
    grid_logit_recall.fit(X_train,y_train)
    
    ans6 = grid_logit_recall.cv_results_['mean_test_score']
    
    return ans6

clf_grid = answer_six()
clf_grid

array([ 0.66666667,  0.76086957,  0.80072464,  0.80434783,  0.8115942 ,
        0.8115942 ,  0.80797101,  0.8115942 ,  0.80797101,  0.8115942 ])

In [168]:
clf_grid.reshape(5,2)

array([[ 0.66666667,  0.76086957],
       [ 0.80072464,  0.80434783],
       [ 0.8115942 ,  0.8115942 ],
       [ 0.80797101,  0.8115942 ],
       [ 0.80797101,  0.8115942 ]])

In [ ]:
%matplotlib notebook
import seaborn as sns
import matplotlib.pyplot as plt

# Use the following function to help visualize results from the grid search
def GridSearch_Heatmap(scores):
    plt.figure()
    sns.heatmap(scores.reshape(5,2), xticklabels=['l1','l2'], yticklabels=[0.01, 0.1, 1, 10, 100])
    plt.yticks(rotation=0);

GridSearch_Heatmap(answer_six())